name: google_map_live
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.3.0
  location: ^4.4.0
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  permission_handler: ^10.3.0
  url_launcher: ^6.2.5
  syncfusion_flutter_pdfviewer: ^22.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dsBuffer.png
    - assets/logo.png 
    - assets/cv.pdf